#!/usr/bin/env python3
"""Generate the offline entry point from the one maintained core rule file."""
import argparse
import json
from pathlib import Path


def render(root: Path) -> str:
    source = (root / "SKILL.md").read_text(encoding="utf-8")
    if not source.startswith("---\n"):
        raise ValueError("SKILL.md must start with frontmatter")
    body = source.split("---\n", 2)[2].lstrip()
    version = json.loads((root / "dz-manifest.json").read_text())["workflow_version"]
    body = body.replace("](references/", "](../references/")
    return ("<!-- Generated by scripts/sync_workflow.py; edit SKILL.md, not this file. -->\n"
            f"# DZ Universal Workflow — {version}\n\n"
            "For a plain-chat host, paste this complete file. Core decisions work without the linked "
            "references; unavailable detailed procedures or execution capabilities remain unverified. "
            "Use actual tools and current project records when available; never invent them.\n\n" + body)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    target = root / "portable/DZ-UNIVERSAL.md"
    expected = render(root)
    if args.check:
        if not target.is_file() or target.read_text(encoding="utf-8") != expected:
            print("Portable workflow is stale; run scripts/sync_workflow.py")
            return 1
        print("Portable workflow matches the canonical Skill")
    else:
        target.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
